#!/bin/bash

# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

set -euxo pipefail

reuse lint
black --check --diff .
isort --check --diff .
mypy
pytest
