# SPDX-FileCopyrightText: 2025 David Mandelberg <david@mandelberg.org>
#
# SPDX-License-Identifier: Apache-2.0

on:
  push: {}
  schedule:
  - cron: '56 19 * * 0'

jobs:
  test:
    strategy:
      matrix:
        python-version:
        - '3.12'
        - '3.13'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install -y reuse
        python -m pip install --upgrade pip
        pip install '.[test]'
    - name: Test
      run: |
        ./test
  install-test:
    strategy:
      matrix:
        python-version:
        - '3.12'
        - '3.13'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python package
      run: |
        python -m pip install --upgrade pip
        pip install pipx
        pipx install .
    - name: Generate input method
      run: |
        mkdir output
        unimnim --output=output
    - name: Upload input method
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output
        if-no-files-found: error
